@extends('layout')
@section('content')
<style>
.article-head{padding:65px 0 42px;text-align:center;background:linear-gradient(150deg,#eef8ff,#f8fbff)}.article-head h1{max-width:850px;margin:15px auto;font-size:48px;line-height:1.15}.article-meta{color:#6d809b;font-size:13px}.article-wrap{max-width:850px;margin:0 auto;padding:45px 22px 75px}.article-cover{width:100%;height:auto;aspect-ratio:16/9;object-fit:cover;margin-bottom:34px;border-radius:18px;box-shadow:0 18px 45px #254f8520}.article-content{color:#263c59;font-size:17px;line-height:1.8}.article-content h2,.article-content h3{margin-top:34px;color:#152746}.article-content img{max-width:100%;height:auto;border-radius:12px}.article-content iframe{width:100%}.article-content table{display:block;max-width:100%;overflow-x:auto;border-collapse:collapse}.article-content pre,.article-content code{max-width:100%;white-space:pre-wrap;overflow-wrap:anywhere}.article-content a{color:#2166f3;text-decoration:underline}.article-content blockquote{margin:25px 0;padding:15px 20px;border-left:4px solid #2166f3;background:#f1f7ff}.article-back{display:inline-flex;align-items:center;gap:7px;margin-bottom:24px;color:#2166f3;font-weight:700}@media(max-width:600px){.article-head{padding:44px 0 34px}.article-head h1{font-size:34px}.article-wrap{padding:34px 16px 55px}.article-content{font-size:15px;line-height:1.75}.article-content h2{font-size:25px}.article-content h3{font-size:20px}.article-content blockquote{margin:20px 0;padding:13px 15px}}
</style>
<main>
    <header class="article-head"><div class="wrap"><div class="eyebrow">Save-Froms Blog</div><h1>{{ $post->title }}</h1><div class="article-meta"><i class="bi bi-calendar3"></i>&nbsp; {{ optional($post->published_at)->format('F d, Y') ?: $post->created_at->format('F d, Y') }}</div></div></header>
    <article class="article-wrap">
        <a class="article-back" href="{{ route('blog') }}"><i class="bi bi-arrow-left"></i>Back to Blog</a>
        @if($post->featured_image)<img class="article-cover" src="{{ Str::startsWith($post->featured_image, ['http://','https://']) ? $post->featured_image : asset($post->featured_image) }}" alt="Illustration for {{ $post->title }}" title="{{ $post->title }}" width="1280" height="720" fetchpriority="high" decoding="async">@endif
        <div class="article-content">{!! $post->content !!}</div>
    </article>
</main>
@endsection
@push('head')
<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'BlogPosting', 'mainEntityOfPage' => ['@type' => 'WebPage', '@id' => route('blog.show', $post->slug)], 'headline' => $post->title, 'description' => $post->meta_description ?: $post->excerpt, 'image' => $post->featured_image ? [Str::startsWith($post->featured_image, ['http://','https://']) ? $post->featured_image : asset($post->featured_image)] : [asset('images/hero-landscape.png')], 'datePublished' => optional($post->published_at)->toIso8601String(), 'dateModified' => $post->updated_at->toIso8601String(), 'author' => ['@type' => 'Organization', 'name' => 'Save-Froms Editorial Team', 'url' => route('blog')], 'publisher' => ['@type' => 'Organization', 'name' => 'Save-Froms', 'logo' => ['@type' => 'ImageObject', 'url' => asset('images/save-froms-logo.svg')]], 'inLanguage' => 'en'], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
<script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'BreadcrumbList', 'itemListElement' => [['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => route('home')], ['@type' => 'ListItem', 'position' => 2, 'name' => 'Blog', 'item' => route('blog')], ['@type' => 'ListItem', 'position' => 3, 'name' => $post->title, 'item' => route('blog.show', $post->slug)]]], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
@endpush
